# Generated by Django 3.2.5 on 2021-07-08 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auctionlisting_liquid'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionbid',
            name='listingnameid_bid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='listingcomment',
            name='listingnameid_comm',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='listingwatchlist',
            name='listingnameid_watchlist',
            field=models.IntegerField(default=0),
        ),
    ]
